### ISSUE TITLE
Assert vs t_true

### ISSUE THREAD

**Issue by grahamwren** [yifeir33/cs4500#8]
Using the provided test utils from one of the warm-ups (e.g. `Ok`, `Fail`, `t_true`) makes testing much more difficult than using `assert(...)` vs `assert(!...)`.

This is because Assertion Errors will print the assertion which failed, whereas `Fail` will just call `exit(1)` without telling you which test actually failed. Meaning the only way to tell which failed is to start commenting out tests.

We can open a PR to update the current tests but just FYI please use `assert` going forward.

**Comment by NeilResnik** [comment]
Fixed this issue on my own commit. Please use the API in assignment1/part2 from now on, as I felt the duplication w/ submission was confusing. If you feel we did not completely resolve this issue please follow up and I will reopen this.
